#!/usr/bin/env bash

SELF="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NS_UTS="${SELF}/ns-uts"

if [ ! -f "$NS_UTS" ]; then
    touch "$NS_UTS"
else
    if mount | grep -q "$NS_UTS"; then
        umount "$NS_UTS"
    fi
fi

unshare --uts="$NS_UTS" "${SELF}/change-hostname"

